site_name: 《计算机科学中的随机过程》习题书
theme:
  name: material
  language: zh
  font:
    code: Roboto Mono
  features:
    - navigation.tabs # 开启顶部导航栏
    - navigation.indexes # 允许点击文件夹名称进入对应汇总页
    - content.code.copy # 代码块复制按钮

nav:
  - 首页:
      - 首页: index.md
      - 题目更新日志: update_log.md
      # - 安全守则: code_of_conduct.md
  - 习题与解答:
      - 第一章: 
        - 练习: exercises/chapter_01_exercises.md
        - 问题: exercises/chapter_01_problems.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:          # 注意这里加了冒号
      base_path: docs           # 这一行告诉插件：所有小剪刀路径都从 docs 文件夹开始算！

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/heading-numbering.js
  - javascripts/inline-tabs.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
