name: PR Preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: pip install mkdocs-material

      - name: Build MkDocs site
        if: github.event.action != 'closed'
        run: mkdocs build

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site/